// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abhsktbtvcsgwfftfkwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiaHNrdGJ0dmNzZ3dmZnRma3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzI0NjAsImV4cCI6MjA2OTc0ODQ2MH0.o9nSKRfcmavve_2X_HlAgv1kBsaUBVJa4sXTu4uFvNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});